//! The eleven cross-cutting typed string identifiers.
//!
//! Each is a `#[repr(transparent)]` newtype over `Arc<str>` (the Rust IDs are
//! `UUIDv4` strings and prefixed strings such as `root-<hex16>`, so the inner
//! type is a string slice, never an integer — hence not `Copy`). `Arc<str>`
//! makes the pervasive id clones across the control plane O(1) atomic refcount
//! bumps rather than heap allocations, while keeping the value immutable after
//! mint. All are generated by the `pub(crate)` [`define_id!`] codegen helper
//! (DRY); it is an internal helper, not a public extension point, and is not
//! re-exported.

/// Generate a transparent string-newtype identifier with the standard surface:
/// `Display`/`FromStr`, `TryFrom<String>`/`TryFrom<&str>` (parse-don't-validate,
/// `Error = CoreError`), transparent serde, `JsonSchema`, `as_str`,
/// `into_inner`, and (with the `mint` keyword) `new_v4`.
///
/// `Display` writes the bare inner string (no `kind:` prefix) so
/// `id.to_string().parse() == Ok(id)` is lossless and DB/JSON columns stay
/// byte-identical to the Rust strings. The non-empty invariant is enforced on
/// every fallible construction path (`FromStr`/`TryFrom`) via
/// [`CoreError::EmptyId`](crate::CoreError::EmptyId).
macro_rules! define_id {
    ($(#[$meta:meta])* $name:ident, mint) => {
        define_id!(@core $(#[$meta])* $name);
        impl $name {
            /// Mint a fresh dashed `UUIDv4`-backed identifier. The runtime's
            /// prefixed mints (`root-{request_id}`, `uuid4().hex[:16]`,
            /// `subagent_<counter>`) are produced by the owning crate, not by
            /// this generic helper.
            #[must_use]
            pub fn new_v4() -> Self {
                Self(::uuid::Uuid::new_v4().to_string().into())
            }
        }
    };
    ($(#[$meta:meta])* $name:ident, no_mint) => {
        define_id!(@core $(#[$meta])* $name);
    };
    (@core $(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(
            Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord,
            ::serde::Serialize, ::schemars::JsonSchema,
        )]
        #[serde(transparent)]
        pub struct $name(::std::sync::Arc<str>);

        impl $name {
            /// Borrow the identifier as a string slice.
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }

            /// Consume the identifier, returning an owned `String` copy of the
            /// inner slice.
            #[must_use]
            pub fn into_inner(self) -> String {
                self.0.as_ref().to_owned()
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl ::core::str::FromStr for $name {
            type Err = $crate::error::CoreError;
            fn from_str(s: &str) -> ::core::result::Result<Self, Self::Err> {
                if s.is_empty() {
                    return ::core::result::Result::Err(
                        $crate::error::CoreError::EmptyId { kind: stringify!($name) },
                    );
                }
                ::core::result::Result::Ok(Self(::std::sync::Arc::from(s)))
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let value = <::std::string::String as ::serde::Deserialize>::deserialize(
                    deserializer,
                )?;
                value.parse().map_err(::serde::de::Error::custom)
            }
        }

        impl ::core::convert::TryFrom<String> for $name {
            type Error = $crate::error::CoreError;
            fn try_from(s: String) -> ::core::result::Result<Self, Self::Error> {
                s.parse()
            }
        }

        impl ::core::convert::TryFrom<&str> for $name {
            type Error = $crate::error::CoreError;
            fn try_from(s: &str) -> ::core::result::Result<Self, Self::Error> {
                s.parse()
            }
        }
    };
}

define_id!(
    /// Identifier for a request row. Minted as `str(uuid.uuid4())` in
    /// `runtime/entry.py`; `new_v4` reproduces that dashed `UUIDv4` shape exactly.
    RequestId,
    mint
);
define_id!(
    /// Identifier for a persisted Task row. Opaque string; the root mint is
    /// `root-{request_id}` (derived by the owning request service from the
    /// injected request id, not `new_v4`).
    TaskId,
    mint
);
define_id!(
    /// Identifier for a delegated Workflow row.
    WorkflowId,
    mint
);
define_id!(
    /// Identifier for an Iteration row.
    IterationId,
    mint
);
define_id!(
    /// Identifier for an Attempt row.
    AttemptId,
    mint
);
define_id!(
    /// Identifier for an agent run (engine agent factory).
    AgentRunId,
    mint
);
define_id!(
    /// Identifier for a provisioned sandbox.
    SandboxId,
    mint
);
define_id!(
    /// Identifier for a single tool use. Model-assigned by the provider stream,
    /// so it has no local `new_v4` mint — minting one would be a bug.
    ToolUseId,
    no_mint
);
define_id!(
    /// Identifier for a sandbox tool-call invocation (tool dispatch).
    InvocationId,
    mint
);
define_id!(
    /// Identifier for a sandbox command-session tool handle.
    CommandSessionId,
    mint
);

#[cfg(test)]
#[path = "../tests/ids/mod.rs"]
mod tests;
