"""Pipeline store protocol — backend-agnostic persistence interface."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from pipeline.models import PipelineCheckpoint, PipelineRun
from pipeline.schema import PipelineConfig


@runtime_checkable
class PipelineStore(Protocol):
    """Backend-agnostic pipeline persistence."""

    # Pipeline definitions
    def save_pipeline(self, config: PipelineConfig) -> None: ...
    def get_pipeline(self, pipeline_id: str) -> PipelineConfig | None: ...
    def list_pipelines(self) -> list[PipelineConfig]: ...
    def delete_pipeline(self, pipeline_id: str) -> bool: ...

    # Runs
    async def create_run(self, run: PipelineRun) -> None: ...
    async def get_run(self, run_id: str) -> PipelineRun | None: ...
    async def update_run(self, run: PipelineRun) -> None: ...
    async def list_runs(self, pipeline_id: str | None = None) -> list[PipelineRun]: ...

    # Checkpoints
    async def save_checkpoint(
        self, run: PipelineRun, checkpoint: PipelineCheckpoint
    ) -> None: ...
    async def get_checkpoint(
        self, run_id: str, checkpoint_id: str
    ) -> PipelineCheckpoint | None: ...
    async def list_checkpoints(self, run_id: str) -> list[PipelineCheckpoint]: ...
