"""Provider-neutral sandbox API contract.

Three Protocols, one shared model module, and an error hierarchy. See
``docs/architecture/sandbox-api-adapter-migration-plan.md`` for the full
layering and dependency rules.
"""

from __future__ import annotations

from sandbox.api.audited_sandbox_api import AuditedSandboxApi
from sandbox.api.code_intelligence_api import CodeIntelligenceApi
from sandbox.api.code_intelligence_impl import SvcCodeIntelligence
from sandbox.api.errors import (
    ProcessTerminated,
    SandboxApiError,
    SandboxConflictError,
    SandboxNotFoundError,
    SandboxTimeoutError,
    SandboxTransportError,
)
from sandbox.api.models import (
    CheckedWriteResult,
    CheckedWriteSpec,
    Diagnostic,
    DiagnosticSeverity,
    DiagnosticsRequest,
    DiagnosticsResult,
    EditFileRequest,
    EditFileResult,
    GlobRequest,
    GlobResult,
    GrepMatch,
    GrepRequest,
    GrepResult,
    MoveFileRequest,
    MoveFileResult,
    ProcessHandle,
    ProcessStatus,
    RawExecResult,
    ReadFileRequest,
    ReadFileResult,
    ReferencesRequest,
    ReferencesResult,
    RemoveFileRequest,
    RemoveFileResult,
    RequestActor,
    SearchMatch,
    SearchReplaceEdit,
    ShellRequest,
    ShellResult,
    SymbolDefinition,
    SymbolQueryConfidence,
    SymbolQueryRequest,
    SymbolQueryResult,
    SymbolReference,
    WorkspaceStatus,
    WorkspaceStructureRequest,
    WorkspaceStructureResult,
    WorkspaceStructureSource,
    WriteFileRequest,
    WriteFileResult,
)
from sandbox.api.sandbox_api import SandboxApi
from sandbox.api.transport import SandboxTransport

__all__ = [
    "AuditedSandboxApi",
    "CheckedWriteResult",
    "CheckedWriteSpec",
    "CodeIntelligenceApi",
    "Diagnostic",
    "DiagnosticSeverity",
    "DiagnosticsRequest",
    "DiagnosticsResult",
    "EditFileRequest",
    "EditFileResult",
    "GlobRequest",
    "GlobResult",
    "GrepMatch",
    "GrepRequest",
    "GrepResult",
    "MoveFileRequest",
    "MoveFileResult",
    "ProcessHandle",
    "ProcessStatus",
    "ProcessTerminated",
    "RawExecResult",
    "ReadFileRequest",
    "ReadFileResult",
    "ReferencesRequest",
    "ReferencesResult",
    "RemoveFileRequest",
    "RemoveFileResult",
    "RequestActor",
    "SandboxApi",
    "SandboxApiError",
    "SandboxConflictError",
    "SandboxNotFoundError",
    "SandboxTimeoutError",
    "SandboxTransport",
    "SandboxTransportError",
    "SearchMatch",
    "SearchReplaceEdit",
    "ShellRequest",
    "ShellResult",
    "SvcCodeIntelligence",
    "SymbolDefinition",
    "SymbolQueryConfidence",
    "SymbolQueryRequest",
    "SymbolQueryResult",
    "SymbolReference",
    "WorkspaceStatus",
    "WorkspaceStructureRequest",
    "WorkspaceStructureResult",
    "WorkspaceStructureSource",
    "WriteFileRequest",
    "WriteFileResult",
]
