//! Console TypeScript bindings: project the three public operation catalogs
//! into request-argument interfaces plus per-scope operation maps.

use std::fmt::Write as _;

use anyhow::{bail, Result};
use sandbox_operation_contract::{
    catalog_from_value, catalog_to_value, ArgKind, OperationCatalog, OperationCatalogDocument,
    OperationScopeKind, OperationScopePolicy, OperationSpecDocument,
};

pub const BINDINGS_RELATIVE_PATH: &str = "web/console/src/api/gen/operations.ts";

const HEADER: &str = "\
// Generated by `cargo run -p xtask -- gen-console-api` from the public
// operation catalogs in crates/sandbox-operations/catalog. Do not edit.
//
// Interfaces describe request `args` only. For sandbox-scoped operations the
// target sandbox id rides in the request scope (`sandboxScope(id)`), never in
// `args`; system-scoped operations keep their `sandbox_id` argument.
";

/// Render the generated TypeScript module for the console SPA.
///
/// # Errors
/// Returns an error when a catalog document is invalid or two catalogs
/// declare the same operation name.
pub fn rendered_bindings() -> Result<String> {
    let catalogs = [
        decoded(sandbox_operation_catalog::manager::manager_catalog())?,
        decoded(sandbox_operation_catalog::runtime::runtime_catalog())?,
        decoded(sandbox_operation_catalog::observability::observability_catalog())?,
    ];

    let mut output = String::from(HEADER);
    let mut system_ops = Vec::new();
    let mut sandbox_ops = Vec::new();
    let mut seen = std::collections::HashSet::new();

    for catalog in &catalogs {
        for operation in &catalog.operations {
            if !seen.insert(operation.name.as_str()) {
                bail!("duplicate operation across catalogs: {}", operation.name);
            }
            let Some(scope_policy) = operation_scope_policy(catalog, &operation.name) else {
                bail!("operation has no public route: {}", operation.name);
            };
            output.push('\n');
            render_interface(&mut output, operation, scope_policy)?;
            for kind in operation_scope_kinds(catalog, &operation.name) {
                match kind {
                    OperationScopeKind::System => system_ops.push(operation.name.clone()),
                    OperationScopeKind::Sandbox => sandbox_ops.push(operation.name.clone()),
                }
            }
        }
    }

    render_map(&mut output, "SystemOpArgs", &system_ops)?;
    render_map(&mut output, "SandboxOpArgs", &sandbox_ops)?;
    output.push('\n');
    output.push_str("export type SystemOp = keyof SystemOpArgs;\n");
    output.push_str("export type SandboxOp = keyof SandboxOpArgs;\n");
    Ok(output)
}

fn decoded(catalog: OperationCatalog) -> Result<OperationCatalogDocument> {
    catalog_from_value(&catalog_to_value(catalog))
        .map_err(|error| anyhow::anyhow!("invalid catalog: {error}"))
}

fn operation_scope_kinds(
    catalog: &OperationCatalogDocument,
    operation: &str,
) -> Vec<OperationScopeKind> {
    catalog
        .routes
        .iter()
        .filter(|route| route.operation == operation)
        .map(|route| route.scope_kind)
        .collect()
}

fn operation_scope_policy(
    catalog: &OperationCatalogDocument,
    operation: &str,
) -> Option<OperationScopePolicy> {
    catalog
        .routes
        .iter()
        .find(|route| route.operation == operation)
        .map(|route| route.scope_policy)
}

fn render_interface(
    output: &mut String,
    operation: &OperationSpecDocument,
    scope_policy: OperationScopePolicy,
) -> Result<()> {
    writeln!(output, "/** {} */", doc_text(&operation.summary))?;
    writeln!(
        output,
        "export interface {} {{",
        interface_name(&operation.name)
    )?;
    let selector_is_scope = scope_policy != OperationScopePolicy::System;
    for arg in &operation.args {
        if selector_is_scope && arg.name == "sandbox_id" {
            continue;
        }
        let mut doc = doc_text(&arg.help);
        if let Some(default) = &arg.default {
            write!(doc, " Default: {}.", doc_text(default))?;
        }
        writeln!(output, "  /** {doc} */")?;
        let optional = if arg.required && arg.default.is_none() {
            ""
        } else {
            "?"
        };
        writeln!(output, "  {}{optional}: {};", arg.name, ts_type(arg.kind))?;
    }
    writeln!(output, "}}")?;
    Ok(())
}

fn render_map(output: &mut String, name: &str, operations: &[String]) -> Result<()> {
    output.push('\n');
    writeln!(output, "export interface {name} {{")?;
    for operation in operations {
        writeln!(output, "  {operation}: {};", interface_name(operation))?;
    }
    writeln!(output, "}}")?;
    Ok(())
}

fn interface_name(operation: &str) -> String {
    let mut name = String::new();
    for part in operation.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            name.extend(first.to_uppercase());
            name.push_str(chars.as_str());
        }
    }
    name.push_str("Args");
    name
}

const fn ts_type(kind: ArgKind) -> &'static str {
    match kind {
        ArgKind::String | ArgKind::Path => "string",
        ArgKind::Integer | ArgKind::Float => "number",
        ArgKind::JsonArray => "unknown[]",
    }
}

fn doc_text(value: &str) -> String {
    value.replace("*/", "*\\/")
}
