"""Description for the run_subagent tool."""

from __future__ import annotations

from tools._names import (
    CANCEL_SUBAGENT_TOOL_NAME,
    CHECK_SUBAGENT_PROGRESS_TOOL_NAME,
    RUN_SUBAGENT_TOOL_NAME,
    SUBMIT_EXPLORATION_RESULT_TOOL_NAME,
)


def get_run_subagent_description() -> str:
    return (
        f"Spawn a registered subagent as a supervised async session. You hand it `prompt` as\n"
        "its only input. It must finish by calling its terminal tool; whatever that\n"
        "terminal tool emits becomes your result.\n"
        "\n"
        "Use this when:\n"
        "- You need to delegate a focused, context-isolated investigation (e.g.,\n"
        "  \"where is X used across the repo?\") so your context isn't polluted by\n"
        "  intermediate tool output.\n"
        "- You can launch multiple independent investigations and want to run them\n"
        f"  in parallel — fire them all in a single message with multiple\n"
        f"  `{RUN_SUBAGENT_TOOL_NAME}` calls.\n"
        "\n"
        "Do NOT use for:\n"
        "- Work you'd handle in 1–3 of your own tool calls — direct execution\n"
        "  beats subagent overhead.\n"
        "- Spawning further subagents from inside a subagent — that path is\n"
        "  rejected at validation time. Handle the work directly, or submit your\n"
        "  findings via your own terminal tool.\n"
        "- Tasks that need shared context with you — the subagent does NOT\n"
        "  inherit your conversation. The `prompt` is the only channel.\n"
        "\n"
        "Writing the prompt:\n"
        "Brief the subagent like a smart colleague who just walked into the room.\n"
        "It hasn't seen your conversation, doesn't know what you've tried, doesn't\n"
        "understand why the task matters.\n"
        "- Explain what you're trying to accomplish and why.\n"
        "- Include the exact paths, symbol names, or commands you'd run yourself.\n"
        "- Specify what's in scope and what's out of scope.\n"
        "- Tell it what shape of answer you want (\"report in under 200 words\",\n"
        "  \"list the file paths\").\n"
        "- Terse command-style prompts produce shallow, generic work.\n"
        "\n"
        "Don't peek. The launch returns a `subagent_session_id`; the subagent\n"
        "runs asynchronously. Don't read its transcript or poll progress unless\n"
        "the user explicitly asks for a status check — that defeats the point\n"
        "of forking off its tool noise. You'll be notified when it completes.\n"
        "\n"
        "Don't race. After launching, you know nothing about what the subagent\n"
        "will find. Never predict its result in any format. If the user asks a\n"
        "follow-up before completion, give status, not a guess.\n"
        "\n"
        "Capabilities and constraints:\n"
        "- The launch returns immediately with a `subagent_session_id`.\n"
        f"- Peek progress with `{CHECK_SUBAGENT_PROGRESS_TOOL_NAME}` — you get\n"
        "  the last few messages while it's running, the terminal output once it\n"
        "  finishes.\n"
        f"- Cancel with `{CANCEL_SUBAGENT_TOOL_NAME}`.\n"
        "- A subagent that exits without calling a terminal tool is marked\n"
        "  failed.\n"
        "\n"
        "Output shape:\n"
        "- On success: the terminal tool's output text (e.g., the\n"
        f"  `{SUBMIT_EXPLORATION_RESULT_TOOL_NAME}.summary`).\n"
        "- On crash: `is_error=True`; the output explains the crash.\n"
        "- On exit without terminal: `is_error=True`, \"subagent exited without\n"
        "  calling a terminal tool\".\n"
        "- Metadata includes `subagent_terminal_called` so `check`/`wait` can\n"
        "  distinguish \"finished cleanly\" from \"finished without delivering\".\n"
        "\n"
        "Example:\n"
        "  run_subagent(\n"
        "    agent_name=\"explorer\",\n"
        "    prompt=(\n"
        "      \"Find every call site of \"\n"
        "      \"`AttemptOrchestrator.apply_reducer_submission` in backend/src \"\n"
        "      \"and report (file, line, calling function). The signature is \"\n"
        "      \"changing in PR #842; I need the punch list of files to update. \"\n"
        "      \"Report under 200 words.\"\n"
        "    ),\n"
        "  )"
    )
